### ISSUE TITLE
Ошибка "Cannot find module 'katex'" 

### ISSUE THREAD

**Issue by sofit** [diplodoc-platform/cli#635]
В md файле есть строка:
`Для пользователей MacBook необходимо еще указать параметр *-Dmaven.home=${maven.home}*. *${maven.home}* - путь до папки, где находится maven.`
эта строка приводит к ошибке 
```
Cannot find module 'katex'
10:24:21   Require stack:
10:24:21   - /usr/lib/node_modules/@diplodoc/cli/node_modules/@diplodoc/latex-extension/plugin/index.js
10:24:21   - /usr/lib/node_modules/@diplodoc/cli/build/index.js
10:24:21       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
10:24:21       at Function.Module._load (internal/modules/cjs/loader.js:774:27)
10:24:21       at Module.require (internal/modules/cjs/loader.js:1003:19)
10:24:21       at require (internal/modules/cjs/helpers.js:107:18)
10:24:21       at eval (eval at dynrequire (/usr/lib/node_modules/@diplodoc/cli/node_modules/@diplodoc/latex-extension/plugin/index.js:47:10), <anonymous>:1:1)
10:24:21       at dynrequire (/usr/lib/node_modules/@diplodoc/cli/node_modules/@diplodoc/latex-extension/plugin/index.js:47:10)
10:24:21       at Object.math_inline (/usr/lib/node_modules/@diplodoc/cli/node_modules/@diplodoc/latex-extension/plugin/index.js:225:7)
10:24:21       at Renderer.renderInline (/usr/lib/node_modules/@diplodoc/cli/node_modules/markdown-it/lib/renderer.js:275:28)
10:24:21       at Renderer.render (/usr/lib/node_modules/@diplodoc/cli/node_modules/markdown-it/lib/renderer.js:330:22)
10:24:21       at /usr/lib/node_modules/@diplodoc/cli/node_modules/@diplodoc/transform/lib/md.js:91:34 {
10:24:21     code: 'MODULE_NOT_FOUND',
10:24:21     requireStack: [
10:24:21       '/usr/lib/node_modules/@diplodoc/cli/node_modules/@diplodoc/latex-extension/plugin/index.js',
10:24:21       '/usr/lib/node_modules/@diplodoc/cli/build/index.js'
10:24:21     ]
10:24:21   }
```

**Comment by 3y3** [comment]
Исправлено в последних версиях. Проверьте пожалуйста.

**Comment by sofit** [comment]
Ошибка осталась

yfm --version
Build time: 13.866ms
4.13.3


```
No such file or has no access to C:\<some-path>\tmp\.tmp_input\ru\developer-guide\Разворачивание_рабочего_места_разработчика_и_тестировщика.md Error: Cannot find module 'katex'
Require stack:
- C:\<some-path>\AppData\Roaming\npm\node_modules\@diplodoc\cli\node_modules\@diplodoc\latex-extension\plugin\index.js
- C:\<some-path>\AppData\Roaming\npm\node_modules\@diplodoc\cli\build\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at eval (eval at dynrequire (C:\<some-path>\AppData\Roaming\npm\node_modules\@diplodoc\cli\node_modules\@diplodoc\latex-extension\plugin\index.js:47:10), <anonymous>:1:1)
    at dynrequire (C:\<some-path>\AppData\Roaming\npm\node_modules\@diplodoc\cli\node_modules\@diplodoc\latex-extension\plugin\index.js:47:10)
    at Object.math_inline (C:\<some-path>\AppData\Roaming\npm\node_modules\@diplodoc\cli\node_modules\@diplodoc\latex-extension\plugin\index.js:225:7)
    at Renderer.renderInline (C:\<some-path>\AppData\Roaming\npm\node_modules\@diplodoc\cli\node_modules\markdown-it\lib\renderer.js:275:28)
    at Renderer.render (C:\<some-path>\AppData\Roaming\npm\node_modules\@diplodoc\cli\node_modules\markdown-it\lib\renderer.js:330:22)
    at C:\<some-path>\AppData\Roaming\npm\node_modules\@diplodoc\cli\node_modules\@diplodoc\transform\lib\md.js:91:34 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\<some-path>\\AppData\\Roaming\\npm\\node_modules\\@diplodoc\\cli\\node_modules\\@diplodoc\\latex-extension\\plugin\\index.js',
    'C:\\<some-path>\\AppData\\Roaming\\npm\\node_modules\\@diplodoc\\cli\\build\\index.js'
  ]
}
```

**Comment by 3y3** [comment]
Добавил зависимость явным образом.
В 4.14.0 должно быть исправлено

**Comment by sofit** [comment]
да, теперь работает
